### PR TITLE
Array serialization bug

### PR DESCRIPTION
**Pull request by kiahn-johnston**

### CODE REVIEW

**Comment by kiahn-johnston** [comment]
this is for WIDGET-223

**Comment by kiahn-johnston** [comment]
the problem was that the viewer/author sends actual array objects. On getting the initial batch of capi properties they were stored in the transporter before the sim had exposed anything. On expose it would grab the waiting values and send them back to the viewer/author, which was an actual array and the widget modal menu freaks out

**Comment by benbarefield** [comment]
this could potentially break some lessons if the Adaptivity app were updated with it. Saying this just so that everyone has it in their heads that if we do an adaptivity app release, we should bump the major version number

**Comment by kiahn-johnston** [comment]
Thanks Ben. Do you have an example I could look at to see how it breaks?

**Comment by benbarefield** [comment]
I don't know for sure if it will, but we do things in CSUEB like: 

1. initialize a property as a string to [hello there]
2. in a trap state, set that property as a string to [{property name}, another entry!]

this results in the property being an array like [hello there,another entry!]

I shared the class with you if you want to look at the lessons

**Comment by jennifermckenzie** [comment]
@kiahn-johnston @benbarefield can we make a comment on adaptivity readme with this info?

**Comment by kiahn-johnston** [comment]
Sorry, didnt get around to replying to your comment Ben, I can test the scenario you mention. Otherwise it sounds good to have it as a breaking change, but isnt it bumping the simcapi major instead of adaptivity app?

**Comment by kiahn-johnston** [comment]
I fixed the simcapi version in the adaptivity app

**Pull request merged**
